---
title: "Mulivariate Viz"
---


Use this file for practice with the **mulivariate viz** in-class activity.  Refer to the class website for details.

```{r}
library(tidyverse)

# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  

# Check out the first 6 rows
# What are the units of observation?
head(weather)

# How many data points do we have? 


# What type of variables do we have?


# Plot 1 (no facets & starting from a density plot of temp3pm)
ggplot(weather, aes(x = temp3pm)) + 
  geom_density()
#3pm temp by location
ggplot(weather, aes(x = temp3pm,)) +
  geom_bar() + facet_wrap(~ location)
```

```{r}
# Multivariate! New examples!

#Example 5: 

# Plot temp3pm vs temp9am
# Change the code in order to indicate the location to which each data point corresponds
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point()

```

```{r}
#5.3 Exercises (required)
# Import and check out data
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
head(education)

#plot of how the average sat scores vary from state to state.
ggplot(education, aes(x = sat)) + geom_density()

# Construct a plot of sat vs expend
# Include a "best fit linear regression model" (HINT: method = "lm")
ggplot(education, aes(x = sat, y = expend)) + geom_point() + geom_smooth(method = "lm")

# Construct a plot of sat vs salary
# Include a "best fit linear regression model" (HINT: method = "lm")
ggplot(education, aes(x = sat, y = salary)) + geom_point() + geom_smooth(method = "lm")

#It seems that as sat score increases, expend and salary decrease.

#Exercise 3: Sat vs salary & expend
ggplot(education, aes(x = sat, y = expend, z = salary)) + geom_point()

```
